openapi: 3.0.0
info:
  title: MCP Link Calculator API
  description: 计算器工具API - 提供基本的数学运算功能
  version: 1.0.0
  contact:
    name: MCP Link Project
    url: https://github.com/beardog6/mcp-link

servers:
  - url: http://localhost:8080
    description: 本地开发服务器

paths:
  /calculator:
    post:
      summary: 执行数学计算
      description: 根据提供的操作数和操作符执行基本的数学运算
      operationId: calculate
      tags:
        - Calculator
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CalculatorRequest'
            example:
              operand1: 10
              operand2: 5
              operator: "+"
      responses:
        '200':
          description: 计算成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CalculatorResponse'
              example:
                result: 15
        '400':
          description: 请求参数错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                invalidOperator:
                  summary: 无效操作符
                  value:
                    error: "Invalid operator. Use +, -, *, or /"
                invalidFormat:
                  summary: 请求格式错误
                  value:
                    error: "Invalid request format"
                divisionByZero:
                  summary: 除零错误
                  value:
                    error: "Division by zero is not allowed"
        '405':
          description: 方法不允许
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error: "Method not allowed"

components:
  schemas:
    CalculatorRequest:
      type: object
      required:
        - operand1
        - operand2
        - operator
      properties:
        operand1:
          type: number
          format: float
          description: 第一个操作数
          example: 10
        operand2:
          type: number
          format: float
          description: 第二个操作数
          example: 5
        operator:
          type: string
          description: 数学操作符
          enum: [+, -, *, /]
          example: "+"
      description: 计算器请求参数

    CalculatorResponse:
      type: object
      properties:
        result:
          type: number
          format: float
          description: 计算结果
          example: 15
        error:
          type: string
          description: 错误信息（如果有）
          example: null
      description: 计算器响应结果

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: 错误描述信息
          example: "Invalid request format"
      description: 错误响应格式

tags:
  - name: Calculator
    description: 计算器相关接口
